
print("welcome to program mash")
import time 
print("v0.6-IN")
time.sleep(0.5) 
print("programs in v0.6-IN in order")
time.sleep(0.3)
print("program mash intro")
time.sleep(0.3)
print("repeat")
time.sleep(0.3)
print("the quiz")
time.sleep(0.3)
print("afk sim")
time.sleep(0.3)
print("money")
time.sleep(0.5)
print("hello")
print("whats ur name")
name = input("say something: ")
print("hello", name)
print("are you ready for the biggest waste of time ever?")
time.sleep(0.3)
whattheysaidatthebeginning = input("say something: ")
time.sleep(0.3)
print("well i dont care if you said yes or no or something else im saving that for later and lets go")
time.sleep(1)
print("just so you know, all of your inputs, including", name, "and", whattheysaidatthebeginning, "are saved. if you put something stupid, itll carry on throughout the program. be smart")
time.sleep(2)
print("first program: repeat")
time.sleep(0.5)
print("||different sub-program|| we have entered repeat. this is all the functions of my app repeat, but in this program.")
time.sleep(0.5)
print("say something to have it repeated. [and saved dont forget]")
repeat = input("say something: ")
print("repeating...")
time.sleep(0.6)
print("You said", repeat,"!")
time.sleep(1)
print("second program: the quiz")
time.sleep(1)
print("||different sub-program|| we have entered the quiz. its just a short quiz")
time.sleep(2)
print("do you want this quiz to be utter garbage?")
time.sleep(0.5)
uttergarbage = input("say something: ")
print("well if you said no too bad its very bad.")
time.sleep(0.5)
print("what is your favorite color?")
time.sleep(0.5)
color = input("say something: ")
time.sleep(0.5)
print("what is your opinion on rocks?")
time.sleep(0.5)
rocks = input("say something: ")
time.sleep(0.5)
print("what is your favorite food?")
time.sleep(0.5)
food = input("say something: ")
print("what is your opinion on micro usb? [the type of connectors that were in non-apple phones a while ago] i dont like it.")
time.sleep(0.5)
microusb = input("say something: ")
time.sleep(1)
print("this is the end of the quiz.")
time.sleep(0.6)
print("im gonna go make some food. meanwhile ill just make you sit through my game afk sim.")
time.sleep(1)
print("1")
time.sleep(1)
print("2")
time.sleep(1)
print("3")
time.sleep(1)
print("4")
time.sleep(1)
print("5")
time.sleep(0.5)
print("food is done.")
time.sleep(0.5)
print("i made some", food)
time.sleep(0.5)
print("i hope u like")
time.sleep(0.5)
debugbreak = input("DEBUG BREAK, pls type anything")
time.sleep(0.5)
print("heres a program that i keep recoding.")
time.sleep(0.5)
print("its called money")
time.sleep(1)
print("how much monets?")
time.sleep(0.5)
money = float(input("say something: "))
time.sleep(0.5)
print("you now have", money, "money.")
time.sleep(0.5)
print("but no. you only get 200.")
money = float(200)
time.sleep(0.5)
print("this may be used for future stuff in this program")
time.sleep(0.5)
'''
padding
'''
print("ITS THE HUNDRETH LINE")
print("DODODOOOOODOOOOOO")
print("DOODOODODODO")
print("for my suffering 100 monets have been deducted.")
money -= 100
print("you now have", money, "money.")
if money <= 0:
    time.sleep(0.3)
    print("you dropped below 0 money. you lose. you failed.")
    time.sleep(0.3)
    print("program mash will now shut down")
    time.sleep(0.3)
    exit()
else:
    print("if you ever dip below 0 money, you lose.")
